### ISSUE TITLE
Tests are not halting

### ISSUE THREAD

**Issue by lucis** [chrisgalvan/jest-standard-reporter#25]
Great package, I was really bothered by this Jest problem!

Although, whenever I switch my reporter to `jest-standard-reporter` my `jest` **doesn't stop**. All of the tests are executed and, indeed, with the correct IO piping, but in the end the process doesn't stop.

The `Time:` keeps getting higher until I hit Ctrl + C. Could anyone help me or point out what I could look into?

If I use the default reporter everything goes right

**Comment by chrisgalvan** [comment]
Do you have any repo I can look at?
Does this happens in CI or local?

**Comment by chrisgalvan** [comment]
Closing based on inactivity
