### ISSUE TITLE
Cannot read property 'useStderr' of undefined

### ISSUE THREAD

**Issue by barclayd** [chrisgalvan/jest-standard-reporter#33]
Thanks for this excellent library.

When I run snapshot tests for the first time in a Vue CLI 3 app using ``Jest`` and ``vue-test-utils``, I get the following error:

```script
 ● Test suite failed to run

    TypeError: Cannot read property 'useStderr' of undefined

      at log (node_modules/jest-standard-reporter/src/stdlib.js:14:14)
          at Array.forEach (<anonymous>)
      at StandardReporter.onTestResult (node_modules/jest-standard-reporter/src/jestStandardReporter.js:78:24)
```
This triggers a failure but the snapshot test itself has in fact been written. When I next run the test suite, all tests pass with no failures.

Thanks very much in advance!

**Comment by NikhilVerma** [comment]
Fixed here - https://github.com/chrisgalvan/jest-standard-reporter/pull/36

**Comment by barclayd** [comment]
Awesome, thanks so much @NikhilVerma! 😊

**Comment by chrisgalvan** [comment]
Seems like there is a bracket missing in the code, once you resolve it I can merge it. Thanks much appreciated
